### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by CamsShaft** [elliottophellia/kaga#1]
I have it running in my browser, but everything I do brings up the same error: 

Fatal error: Uncaught ValueError: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty in /data/data/com.termux/files/home/tulip/index.php:88 Stack trace: #0 /data/data/com.termux/files/home/tulip/index.php(88): DOMDocument->loadHTML('') #1 {main} thrown in /data/data/com.termux/files/home/tulip/index.php on line 88

Not sure where to go from here and the Readme and index are not helpful either.... other than that, well nothing really to say about it.

**Comment by elliottophellia** [comment]
Which PHP version did you use?

**Comment by elliottophellia** [comment]
Issue closed because the issue no longer relevant
